name: Merge main into develop via Pull Request

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_main_into_develop:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create PullRequest
        run: |
          gh pr list --base develop --head main --state open --json number -q '. | length' > pr_count.txt
          PR_COUNT=$(cat pr_count.txt)
          if [ "$PR_COUNT" -eq 0 ]; then
            gh pr create --base develop --head main --title "Merge main into develop" --body "mainの内容をdevelopに取り込みます"
          fi

      - name: Approve PR
        run: |
          PR_NUMBER=$(gh pr list --base develop --head main --state open --json number -q '.[0].number')
          gh pr review "$PR_URL" --approve

      - name: Merge PullRequest
        run: |
          PR_NUMBER=$(gh pr list --base develop --head main --state open --json number -q '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --merge --admin
          fi